version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    container_name: fast-api-web
    ports:
      - "8000:15400"
    volumes:
      - ./fast_app/:/fast_app
